### PR TITLE
Improvement/codebase fix

### PR DESCRIPTION
**Pull request by KevinCounts**
Structure changes to make score_db an installable package. All src files have been moved to scr/score_db/. All imports have been updated to reference score_db since the package is not longer referenced directly in the python path. Unit tests have also been updated to use the db_request_name for easier user reference.

### CODE REVIEW

**Comment by KevinCounts** [comment]
The readme also needs to be updated to fix the db_request_name changes, but I'm going to put that in a separate pull request since the installation instructions also need to be refactored and likely discussed more in depth.

**Comment by jrknezha** [comment]
> The readme also needs to be updated to fix the db_request_name changes, but I'm going to put that in a separate pull request since the installation instructions also need to be refactored and likely discussed more in depth.

@KevinCounts  could you please but the readme change for db_request_name changes in this PR as well? It should be all kept together, especially since the installation instructions is a separate and more discussion necessary issue. Or revert the changes from the tests. Since the appendix of the readme is even based on the tests, they definitely should be corrected at the same time.

**Comment by KevinCounts** [comment]
Readme changes for db_request_name are here now. I also updated .env_example and setup.cfg to have more accurate info

**Comment by jrknezha** [comment]
@KevinCounts looks good and it works with score monitoring as expected, only thing left is could you please address the merge conflicts?

**Review by jrknezha — APPROVED** [review]
Very useful changes both to the documentation and stability and the ability to install as a package.

**Pull request merged**
